### PR TITLE
Multiple tours

### PR DESCRIPTION
**Pull request by b-steel**
I wanted to be able to support multiple tours within my app (on different pages, or just on the same page but on different use cases potentially) so I made this fork.  I basically made keyed objects so you can (optionally) input a tourKey when using the useTourGuideController hook and receive functions (and components) that are keyed to that string.  

Updated the README file with an example

Made a lot of revisions and changes (and one little bugfix in there too (1st commit)).  Feel free to take what I started and make your own changes if you like the direction it's going but don't feel this is enough.  

I tested it a bit for backwards compatibility but not crazily extensively.  

Cheers

### CODE REVIEW

**Comment by donatoaguirre24** [comment]
@xcarpentier can you please review this? Thanks in advance!

**Comment by isati** [comment]
This doesn't appear to work as advertised. Passing in the tourKey stops the eventEmitter being defined correctly.

`TypeError: Cannot read properties of undefined (reading 'on')
(anonymous function)
/home/sati/Temp/rn-tourguide/App.tsx:44
  41 | }, [canStart]) // wait until everything is registered
  42 | 
  43 | React.useEffect(() => {
> 44 |   eventEmitter.on('start', () => console.log('start'))
     | ^  45 |   eventEmitter.on('stop', () => console.log('stop'))
  46 |   eventEmitter.on('stepChange', () => console.log(`stepChange`))
  47 |   return () => eventEmitter.off('*', null)`

**Comment by xcarpentier** [comment]
on it

**Comment by julhernandezv** [comment]
No support for this package anymore @xcarpentier ?

**Comment by genesisbell** [comment]
Implement this pleaseeee, this is really useful!

**Comment by slytter** [comment]
Nice work @b-steel 
We have hosted your implementation at https://www.npmjs.com/package/@climaider/rn-tourguide since @xcarpentier seems unavailable, we will take it down whenever this branch is merged

**Comment by santiagofm** [comment]
@xcarpentier Hey Xavier, can we get a new release ?

**Comment by zienna** [comment]
@xcarpentier +1

**Comment by ansh** [comment]
@xcarpentier Can you create a new release of this library at the very least?

**Comment by zienna** [comment]
@xcarpentier please dude

**Pull request merged**
